name: Update Files and Create Release

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: python get.py

    - name: Check for changes
      run: |
        git status
        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "Update files"
          git push https://github.com/${{ github.repository }} HEAD:main
        else
          echo "No changes to commit"
        fi
      env:
        PAT: ${{ secrets.PAT }}

    - name: Create GitHub Release
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"tag_name": "v1.0.0", "name": "每日节点", "body": "Release version 1.0.0"}' "https://api.github.com/repos/${{ github.repository }}/releases" -H "Authorization: token ${{ secrets.PAT }}"
      env:
        PAT: ${{ secrets.PAT }}
