name: Update Files

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: python get.py

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update files"
        git push https://github.com/${{ github.repository }} HEAD:main
      env:
        PAT: ${{ secrets.PAT }}
    - name: Update GitHub Release
      run: |
        curl -X PATCH -H "Content-Type: application/json" -d '{"name": "每日节点", "body": "新节点"}' "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}" -H "Authorization: token ${{ secrets.PAT }}"
      env:
        PAT: ${{ secrets.PAT }}

