name: Update Nodes API

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: |
        python get.py

    - name: Check for changes
      run: |
        git status
        if [[ $(git status --porcelain nodefree.txt nodeshare.txt clashgithub0.txt clashgithub1.txt clashgithub2.txt clashgithub3.txt clashgithub4.txt ) ]]; then
          git add nodefree.txt
          git add nodeshare.txt
          git add clashgithub0.txt
          git add clashgithub1.txt
          git add clashgithub2.txt
          git add clashgithub3.txt
          git add clashgithub4.txt
          git status
          git commit -m "Update files"
          git push https://github.com/${{ github.repository }} HEAD:main
        else
          echo "No changes to commit"
        fi
      env:
        PAT: ${{ secrets.PAT }}
    
    
